# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nuxt CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    env:
      PAGE_URL : ${{secrets.PAGE_URL}}
      BLOG_URL : ${{secrets.BLOG_URL}}
      FORM_URL : ${{secrets.FORM_URL}}

    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: pm2 start ~/actions-runner/_work/Indian-Inspire-Of-Sport/Indian-Inspire-Of-Sport/ecosystem.config.js
